// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2FWafVBerOFwtpxrynuTCMecHRT0JJk',
    appId: '1:104064784819:web:d2d348fdd55d694ed553c6',
    messagingSenderId: '104064784819',
    projectId: 'moda-gulay-butik-bbcd7',
    authDomain: 'moda-gulay-butik-bbcd7.firebaseapp.com',
    storageBucket: 'moda-gulay-butik-bbcd7.appspot.com',
    measurementId: 'G-0HWC6P39MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMc-zCGEcZlZnF6RRD5Wyzexd_yUXMXc',
    appId: '1:104064784819:android:fd79a359f181fc40d553c6',
    messagingSenderId: '104064784819',
    projectId: 'moda-gulay-butik-bbcd7',
    storageBucket: 'moda-gulay-butik-bbcd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaUcVvvJeXqSGiGjDMECJGctiHSxrGo4',
    appId: '1:104064784819:ios:a5d0afbaaae24033d553c6',
    messagingSenderId: '104064784819',
    projectId: 'moda-gulay-butik-bbcd7',
    storageBucket: 'moda-gulay-butik-bbcd7.appspot.com',
    iosBundleId: 'com.example.modaGulayButik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaUcVvvJeXqSGiGjDMECJGctiHSxrGo4',
    appId: '1:104064784819:ios:d7ca64856eea5c6fd553c6',
    messagingSenderId: '104064784819',
    projectId: 'moda-gulay-butik-bbcd7',
    storageBucket: 'moda-gulay-butik-bbcd7.appspot.com',
    iosBundleId: 'com.example.modaGulayButik.RunnerTests',
  );
}
